### ISSUE TITLE
Convert label output to Geojson

### ISSUE THREAD

**Issue by Lesstat** [trump-fmi/osm_label_server#1]
The output of server is currently a custom json format. This should be converted to geojson. This makes it easier for clients to conusme.

RFC: https://datatracker.ietf.org/doc/rfc7946/
Example geojson file: https://openlayers.org/en/v4.1.1/examples/data/geojson/point-samples.geojson

**Comment by Mechks** [comment]
It is possible to create the following format:

    {"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[8.8071646,53.0758196]},"properties":{"name":"Bremen","osm":20982927,"prio":132,"t":3686.835042292192}},{"type":"Feature","geometry":{"type":"Point","coordinates":[8.5865509,53.5522264]},"properties":{"name":"Bremerhaven","osm":660314734,"prio":131,"t":4.751763965397364}},{"type":"Feature","geometry":{"type":"Point","coordinates":[8.6238803,53.170524900000004]},"properties":{"name":"Vegesack","osm":2147118476,"prio":124,"t":2.2440622447579543}},{"type":"Feature","geometry":{"type":"Point","coordinates":[8.528893,53.200157000000004]},"properties":{"name":"Farge","osm":253042611,"prio":31,"t":1.5769136968447124}},{"type":"Feature","geometry":{"type":"Point","coordinates":[8.9351249,53.143155300000004]},"properties":{"name":"Timmersloh","osm":3627273522,"prio":12,"t":1.4922737369836614}}]}

This is missing the crs field of the example file. **Do we need it for our application?** Is it required for correct geoJson (the definition below does not define that). 

> 4.  Coordinate Reference System
> 
>    The coordinate reference system for all GeoJSON coordinates is a
>    geographic coordinate reference system, using the World Geodetic
>    System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units
>    of decimal degrees.  This is equivalent to the coordinate reference
>    system identified by the Open Geospatial Consortium (OGC) URN
>    urn:ogc:def:crs:OGC::CRS84.  An OPTIONAL third-position element SHALL
>    be the height in meters above or below the WGS 84 reference
>    ellipsoid.  In the absence of elevation values, applications
>    sensitive to height or depth SHOULD interpret positions as being at
>    local ground or sea level.
> 
>    Note: the use of alternative coordinate reference systems was
>    specified in [GJ2008], but it has been removed from this version of
>    the specification because the use of different coordinate reference
>    systems -- especially in the manner specified in [GJ2008] -- has
>    proven to have interoperability issues.  In general, GeoJSON
>    processing software is not expected to have access to coordinate
>    reference system databases or to have network access to coordinate
>    reference system transformation parameters.  However, where all
>    involved parties have a prior arrangement, alternative coordinate
>    reference systems can be used without risk of data being
>    misinterpreted.

**Comment by Lesstat** [comment]
I do not think it is required. If the client team needs it we will add it. 
As far as I can see this would be a constant value for us depending on the label file.

**Comment by jsvde** [comment]
OpenLayers uses the crs field to determine the projection. 
If crs is not present the default projection is applied. Maybe we run into problems with mapping GeoJSON data to the mercator map. We will test this if you can provide a sample GeoJSON data of the bremen data set. If problems occur you would simply have to add the crs field with permanent data to all responses, since projection does not change.

[reference](https://github.com/openlayers/openlayers/blob/master/src/ol/format/geojson.js#L456).

**Comment by Mechks** [comment]
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[8.8071646,53.0758196]},"properties":{"name":"Bremen","osm":20982927,"prio":132,"t":3686.835042292192}},{"type":"Feature","geometry":{"type":"Point","coordinates":[8.5865509,53.5522264]},"properties":{"name":"Bremerhaven","osm":660314734,"prio":131,"t":4.751763965397364}},{"type":"Feature","geometry":{"type":"Point","coordinates":[8.6238803,53.170524900000004]},"properties":{"name":"Vegesack","osm":2147118476,"prio":124,"t":2.2440622447579543}},{"type":"Feature","geometry":{"type":"Point","coordinates":[8.528893,53.200157000000004]},"properties":{"name":"Farge","osm":253042611,"prio":31,"t":1.5769136968447124}},{"type":"Feature","geometry":{"type":"Point","coordinates":[8.9351249,53.143155300000004]},"properties":{"name":"Timmersloh","osm":3627273522,"prio":12,"t":1.4922737369836614}}],"crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:OGC:1.3:CRS84"}}}

I switched the library and it should be with the crs now. Is that format okay now?

**Comment by jsvde** [comment]
Thanks.
Results from experiments will follow.

**Comment by jsvde** [comment]
Currently the GeoJSON output misses the field "lbl_fac" that is mandatory for correct rendering. 
Could anyone include it in the server response please? See [here](https://github.com/trump-fmi/osm_label_server/blob/master/main.go#L200)

**Comment by Mechks** [comment]
Fixed in https://github.com/trump-fmi/osm_label_server/commit/095bf979e220632c75b21ea468cb9906ce5fd63b , should be on seeigel at ~20:30
