### ISSUE TITLE
Command line argument for configuring label file

### ISSUE THREAD

**Issue by Lesstat** [trump-fmi/osm_label_server#11]
Currently the label file is hard coded. Before we implement full configuration in #5 we will need an easy way to start the server with a different label file.
Proposal:

```shell
./osm_label_server ~/label-files/germany-latest.osm.pbf.ce
```

**Comment by Mechks** [comment]
Plan is to use flags to have a defined structure and the possibility to extend the parameters later on.
Example https://gobyexample.com/command-line-flags
Doc: https://golang.org/pkg/flag/
If a switch to config files is requested, replacing the lib with [this](https://github.com/vharitonsky/iniflags) would allow to keep all the other code.

**Comment by Mechks** [comment]
Fixed in https://github.com/trump-fmi/osm_label_server/commit/e677f5f0b593e9e12d1c82974e5305d1f2fb0430 (used wrong id, the commit was for this issue)
