### ISSUE TITLE
Add  Cross-Origin Request Blocked flag for error answers 

### ISSUE THREAD

**Issue by Mechks** [trump-fmi/osm_label_server#14]
Context: 

Filip
> * Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://seeigel.informatik.uni-stuttgart.de:8080/label?x_min=-546.328125&x_max=546.328125&y_min=-86.55315137453222&y_max=86.5531513745322&t_min=0.001. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Julian
> Hey Server-Team, habt ihr den Beitrag von Filip im Projektforum gelesen? Er bekommt einen CORS-Error bei dem Request zum Labelserver, habe das gerade auch verifiziert. Das hat ja schon funktioniert, ne Idee was da schiefgelaufen ist?
> hab kurz rumprobiert. Ihr macht einen Sanity-Check ob die x-Werte im Bereich [-180,180] liegen. Die CORS-header werden nur gesetzt, wenn der check bestanden ist. Wäre cool, wenn ihr das updaten könnten :)

Set the flag in go for status 400 answers as well.

**Comment by Mechks** [comment]
Fix would be: 
Add 
`	w.Header().Add("Access-Control-Allow-Origin", "*")
`
to 
```
if result.error != nil {
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(C.GoString(result.error))
		C.free_result(result)
		return
	}
```
I cannot test it at the moment. If everyone else has the time to test it, feel free to fix and test it.

**Comment by Mechks** [comment]
Fixed in https://github.com/trump-fmi/osm_label_server/commit/970f803333ff7b937ccfd83d55b4f71c7b2bf993
Waiting for feedback from client team

**Comment by Lesstat** [comment]
Header is now also set for "Bad Requests"
![cors](https://cloud.githubusercontent.com/assets/1104557/26557001/72a7dbb6-449e-11e7-8bfa-0766189cca59.png)
