### ISSUE TITLE
Install and configure tile server on development VM

### ISSUE THREAD

**Issue by Lesstat** [trump-fmi/osm_label_server#2]
- [x] Install tile server with components
- [x] Autostart on boot
- [x] Apache routes request for /label to labelserver
- [ ] Restart on crash of Labelserver??

**Comment by Mechks** [comment]
**Setting header Access-Control-Allow-Origin:** 
mod_tile is not set up with a own configuration file, so all module configuration is done in 000-default.conf. Added line in `<virtualhost>`: 
`Header set Access-Control-Allow-Origin "*"`

**Comment by Marc42** [comment]
Requests for /label/ and /labelCollections are now rerouted to port 8080.
Necessary Apache modules had to loaded by executing:
`a2enmod proxy`
`a2enmod proxy_http`
Then added these two lines to `<VirtualHost *:80>`:
`ProxyPass /label/ http://localhost:8080/label/`
`ProxyPass /labelCollections http://localhost:8080/labelCollections`
