### ISSUE TITLE
Implement configuration

### ISSUE THREAD

**Issue by Lesstat** [trump-fmi/osm_label_server#5]
The label server should be configurable with a file (or similar) where the label files and the url under which to publish them is specified.

**Comment by Mechks** [comment]
Implementation should contain: 
- Definition for the configuration file (syntax, options)
- Option to pass this file to the osm_label_server (flag/default path in go/could reuse code from #11)
- Read in and creation of a config struct in go
- Start endpoints as defined in the config

Each endpoint config needs at the moment:
- the path to the label file to serve
- the endpoint name (unique!) 

Forbidden format for the config file: xml.

**Comment by Mechks** [comment]
Implemented in https://github.com/trump-fmi/osm_label_server/commit/9162d1a74d3bfa32daad5822dc34f7df212d72f3 
waiting till end of sprint presentation is done before merging into master

**Comment by Mechks** [comment]
Merged in master https://github.com/trump-fmi/osm_label_server/commit/53c33d40f548d257d331b7969c93dc7ea7ec8568, changed install script on seeigel to match new flags. Waiting for deploy to check if working

**Comment by Mechks** [comment]
Seems to work with continuous integration - closed
