### ISSUE TITLE
Configure continous delivery

### ISSUE THREAD

**Issue by Lesstat** [trump-fmi/osm_label_server#8]
When startet should log to file instead of console

**Comment by Mechks** [comment]
Cron job fails (?) with: 

> /home/trump/scripts/deploy_label_server.sh: 5: /home/trump/scripts/deploy_label_server.sh: [[: not found
> Pulled new source. Now building
> package github.com/gorilla/mux: cannot download, $GOPATH not set. For more details see: go help gopath
> package github.com/kpawlik/geojson: cannot download, $GOPATH not set. For more details see: go help gopath
> main.go:36:2: cannot find package "github.com/gorilla/mux" in any of:
> 	/usr/lib/go/src/pkg/github.com/gorilla/mux (from $GOROOT)
> 	($GOPATH not set)
> main.go:37:2: cannot find package "github.com/kpawlik/geojson" in any of:
> 	/usr/lib/go/src/pkg/github.com/kpawlik/geojson (from $GOROOT)
> 	($GOPATH not set)
>

**Comment by Lesstat** [comment]
fixed
